-- Prototyp-Stufe: die Definitionen liegen in prototypes/.
require("prototypes.item-groups.trains")
require("prototypes.gui.styles")
require("prototypes.gui.custom-inputs")
require("prototypes.gui.shortcuts")
require("prototypes.signals.virtual-signals")
require("prototypes.entities.train-stop")
require("prototypes.entities.station-combinator")
require("prototypes.items.train-stop")
require("prototypes.items.station-combinator")
require("prototypes.recipes.train-stop")
require("prototypes.recipes.station-combinator")
require("prototypes.technologies.utl-tech")
require("prototypes.tips.tips")
