-- Map-Einstellungen (runtime-global), im Spiel von Admins änderbar.
data:extend({
  {
    type = "int-setting",
    name = "utl-heartbeat-interval",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximum_value = 60,
    order = "a-a",
  },
  {
    type = "int-setting",
    name = "utl-station-batch-size",
    setting_type = "runtime-global",
    default_value = 20,
    minimum_value = 1,
    maximum_value = 500,
    order = "a-b",
  },
  {
    type = "int-setting",
    name = "utl-max-deliveries-per-cycle",
    setting_type = "runtime-global",
    default_value = 2,
    minimum_value = 1,
    maximum_value = 100,
    order = "a-c",
  },
  {
    type = "bool-setting",
    name = "utl-chaining",
    setting_type = "runtime-global",
    default_value = true,
    order = "a-d",
  },
  {
    type = "int-setting",
    name = "utl-fuel-threshold",
    setting_type = "runtime-global",
    default_value = 40,
    minimum_value = 0,
    maximum_value = 100,
    order = "c-a",
  },
  {
    type = "int-setting",
    name = "utl-alert-no-train-minutes",
    setting_type = "runtime-global",
    default_value = 5,
    minimum_value = 0,
    maximum_value = 120,
    order = "d-a",
  },
  {
    type = "int-setting",
    name = "utl-default-provide-threshold",
    setting_type = "runtime-global",
    default_value = 1000,
    minimum_value = 1,
    maximum_value = 1000000000,
    order = "b-a",
  },
  {
    type = "int-setting",
    name = "utl-default-request-threshold",
    setting_type = "runtime-global",
    default_value = 1000,
    minimum_value = 1,
    maximum_value = 1000000000,
    order = "b-b",
  },
  {
    type = "bool-setting",
    name = "utl-debug-log",
    setting_type = "runtime-global",
    default_value = false,
    order = "z-a",
  },
})
