-- Map-Einstellungen (runtime-global), im Spiel von Admins änderbar.
data:extend({
  {
    type = "int-setting",
    name = "utl-heartbeat-interval",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximum_value = 60,
    order = "a-a",
  },
  {
    type = "int-setting",
    name = "utl-station-batch-size",
    setting_type = "runtime-global",
    default_value = 20,
    minimum_value = 1,
    maximum_value = 500,
    order = "a-b",
  },
  {
    type = "int-setting",
    name = "utl-max-deliveries-per-cycle",
    setting_type = "runtime-global",
    default_value = 2,
    minimum_value = 1,
    maximum_value = 100,
    order = "a-c",
  },
  {
    type = "bool-setting",
    name = "utl-chaining",
    setting_type = "runtime-global",
    default_value = true,
    order = "a-d",
  },
  {
    type = "bool-setting",
    name = "utl-wagon-filters",
    setting_type = "runtime-global",
    default_value = true,
    order = "a-e",
  },
  {
    type = "bool-setting",
    name = "utl-station-output",
    setting_type = "runtime-global",
    default_value = true,
    order = "a-f",
  },
  {
    type = "bool-setting",
    name = "utl-research-required",
    setting_type = "runtime-global",
    default_value = true,
    order = "a-g",
  },
  {
    type = "int-setting",
    name = "utl-fuel-threshold",
    setting_type = "runtime-global",
    default_value = 40,
    minimum_value = 0,
    maximum_value = 100,
    order = "c-a",
  },
  {
    -- Mindest-Treibstoff: darunter bleibt ein Zug im Depot (Warnung), sofern er nicht tanken kann
    type = "int-setting",
    name = "utl-fuel-minimum",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 0,
    maximum_value = 100,
    order = "c-b",
  },
  {
    type = "int-setting",
    name = "utl-alert-no-train-minutes",
    setting_type = "runtime-global",
    default_value = 5,
    minimum_value = 0,
    maximum_value = 120,
    order = "d-a",
  },
  {
    type = "int-setting",
    name = "utl-default-provide-threshold",
    setting_type = "runtime-global",
    default_value = 1000,
    minimum_value = 1,
    maximum_value = 1000000000,
    order = "b-a",
  },
  {
    type = "int-setting",
    name = "utl-default-request-threshold",
    setting_type = "runtime-global",
    default_value = 1000,
    minimum_value = 1,
    maximum_value = 1000000000,
    order = "b-b",
  },
  -- Zeitlimits: Standard für alle Teams; jedes Team kann im UTL-Manager eigene Werte setzen.
  {
    type = "int-setting",
    name = "utl-load-timeout",
    setting_type = "runtime-global",
    default_value = 30,
    minimum_value = 0,
    maximum_value = 3600,
    order = "e-a",
  },
  {
    type = "int-setting",
    name = "utl-unload-timeout",
    setting_type = "runtime-global",
    default_value = 30,
    minimum_value = 0,
    maximum_value = 3600,
    order = "e-b",
  },
  -- Verknüpfung von Fracht und Zeit: „und“ = mindestens so lange warten und bis voll/leer,
  -- „oder“ = höchstens so lange warten.
  {
    type = "string-setting",
    name = "utl-timeout-mode",
    setting_type = "runtime-global",
    default_value = "or",
    allowed_values = { "and", "or" },
    order = "e-c",
  },
  -- Nachladen: wächst der Bedarf, während der Zug noch lädt oder zum Anbieter fährt, kommt die
  -- Menge auf die laufende Ladeliste statt in eine zweite Fahrt (Standard aus)
  {
    type = "bool-setting",
    name = "utl-top-up",
    setting_type = "runtime-global",
    default_value = false,
    order = "e-d",
  },
  -- Zweiter Anbieter: reicht einer nicht für die Zugladung, holt der Zug den Rest bei einem zweiten
  -- Anbieter im selben Netz (Standard aus)
  {
    type = "bool-setting",
    name = "utl-multi-pickup",
    setting_type = "runtime-global",
    default_value = false,
    order = "e-da",
  },
  -- Zweiter Anbieter nur, wenn der Umweg (Luftlinie) höchstens so viel Prozent der direkten
  -- Strecke Anbieter → Abnehmer ausmacht (0 = jeder Umweg erlaubt)
  {
    type = "int-setting",
    name = "utl-multi-pickup-detour",
    setting_type = "runtime-global",
    default_value = 50,
    minimum_value = 0,
    maximum_value = 1000,
    order = "e-db",
  },
  -- Cleanup darf seinen Inhalt wieder anbieten (je Station zusätzlich ein Häkchen, Standard aus).
  -- Hier für die ganze Karte abschaltbar.
  {
    type = "bool-setting",
    name = "utl-cleanup-offer",
    setting_type = "runtime-global",
    default_value = true,
    order = "e-e",
  },
  -- Lager-Stationen (Mindest-/Höchstbestand) für die ganze Karte abschaltbar
  {
    type = "bool-setting",
    name = "utl-storage",
    setting_type = "runtime-global",
    default_value = true,
    order = "e-f",
  },
  -- Team-Leiter, die so viele Tage (Spielzeit) nicht online waren, verlieren die Rechte (0 = nie)
  {
    type = "int-setting",
    name = "utl-leader-inactive-days",
    setting_type = "runtime-global",
    default_value = 3,
    minimum_value = 0,
    maximum_value = 365,
    order = "f-a",
  },
  {
    type = "bool-setting",
    name = "utl-debug-log",
    setting_type = "runtime-global",
    default_value = false,
    order = "z-a",
  },
})
